server:
  port: 8099

spring:
  application:
    name: family-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/task/**
        - id: family-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/family/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
